name: study_assistance
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  file_picker: ^8.1.2
  flutter_html: ^3.0.0
  http: ^1.5.0
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^6.0.3 
  html2md: ^1.3.0
  super_clipboard: ^0.8.6
  markdown: ^7.3.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env