name: study_assistance
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # STATE MANAGEMENT
  provider: ^6.1.2

  # UI & UTILS
  file_picker: ^8.1.3
  flutter_html: ^3.0.0
  http: ^1.5.0
  flutter_dotenv: ^5.2.1
  html2md: ^1.3.0
  super_clipboard: ^0.8.12
  shared_preferences: ^2.5.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  markdown: ^7.3.0
  image_picker: ^1.1.2
  flutter_cache_manager: ^3.4.0
  cached_network_image: ^3.4.1
  flutter_signin_button: ^2.0.0
  path: ^1.8.3 
  flutter_markdown: ^0.6.18 

  # FIREBASE - ALL UPGRADED & COMPATIBLE
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env